runtime: python39
instance_class: F2
entrypoint: gunicorn -b :$PORT main:app --timeout 300

env_variables:
  PYTHONUNBUFFERED: "TRUE"
  FIREBASE_CONFIG_FILE: "f1formula-f6f18-firebase-adminsdk-fbsvc-74edc3c8b3.json"

handlers:
- url: /static
  static_dir: app/static
  secure: always

- url: /.*
  script: auto
  secure: always 